# 행렬(Matrix)

행렬(Matrix)은 숫자나 변수를 사각형 형태로 배열한 것입니다. 행렬은 주로 선형 대수학에서 사용되며, 데이터 분석, 기계 학습 등 다양한 분야에서 활용됩니다.

행렬은 보통 대문자 글자로 표시하며, 각각의 원소는 행(row)과 열(column)의 인덱스로 나타냅니다. 예를 들어, 2x3 행렬 A는 다음과 같습니다.

A = \[
  [a11, a12, a13],
  [a21, a22, a23]
\]

여기서 aij는 i번째 행, j번째 열에 있는 원소를 의미합니다.

## 행렬의 덧셈

두 행렬의 덧셈은 같은 위치에 있는 원소끼리 더하는 것입니다. 예를 들어, 두 행렬 A와 B의 덧셈은 다음과 같습니다.

A = \[
  [1, 2, 3],
  [4, 5, 6]
\]

B = \[
  [7, 8, 9],
  [10, 11, 12]
\]

A + B = \[
  [1+7, 2+8, 3+9],
  [4+10, 5+11, 6+12]
\]

      = \[
  [8, 10, 12],
  [14, 16, 18]
\]

In [1]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Matrix addition
C = A + B
print("Matrix A + B:")
print(C)

Matrix A + B:
[[ 8 10 12]
 [14 16 18]]


## 행렬의 곱셈

두 행렬의 곱셈은 첫 번째 행렬의 행과 두 번째 행렬의 열을 각각 곱한 뒤 더해서 새로운 행렬의 원소로 하는 것입니다. 예를 들어, 두 행렬 A(2x3)와 B(3x2)의 곱셈은 다음과 같습니다.

A = \[
  [1, 2, 3],
  [4, 5, 6]
\]

B = \[
  [7, 8],
  [9, 10],
  [11, 12]
\]

A * B = \[
  [1*7 + 2*9 + 3*11, 1*8 + 2*10 + 3*12],
  [4*7 + 5*9 + 6*11, 4*8 + 5*10 + 6*12]
\]

      = \[
  [58, 64],
  [139, 154]
\]

In [2]:
# Define matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

# Matrix multiplication
D = np.dot(A, B)
print("Matrix A * B:")
print(D)

Matrix A * B:
[[ 58  64]
 [139 154]]


## 행렬의 상수배

행렬의 상수배는 행렬의 각 원소에 상수를 곱하는 것입니다. 예를 들어, 행렬 A와 상수 k의 곱셈은 다음과 같습니다.

A = \[
  [1, 2, 3],
  [4, 5, 6]
\]

k = 2

k * A = \[
  [2*1, 2*2, 2*3],
  [2*4, 2*5, 2*6]
\]

      = \[
  [2, 4, 6],
  [8, 10, 12]
\]

In [3]:
# Define matrix A and scalar k
A = np.array([[1, 2, 3], [4, 5, 6]])
k = 2

# Scalar multiplication
E = k * A
print("Matrix k * A:")
print(E)

Matrix k * A:
[[ 2  4  6]
 [ 8 10 12]]
